# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: i crave data
#logo: ![](assets/images/logo.png)
description: A portfolio in development...
#show_downloads: false
theme: jekyll-theme-minimal
github_username: icravedata
instagram_username: icravedata
