# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: i crave data
#logo: ![](assets/images/logo.png)
description: A portfolio in development...

minima:
    social_links:
    - { platform: github,  user_url: "https://github.com/icravedata" }
    - { platform: instagram, user_url: "https://instagram.com/icravedata" }

#build settings
#show_downloads: false
theme: minima
